### PR TITLE
Better code examples in the readme

### PR DESCRIPTION
**Pull request by epayet**

### CODE REVIEW

**Comment by jthelin** [comment]
Is there any specific reason to switch to using tabs here, as long as whatever is used is used consistently throughout the code samples?

Tabs tend to give very variable results depending on which editor people use.

FWIW, the .NET C# coding style guidelines Item 2 recommends always to use spaces not tabs.
https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

I would suggest might be better to go the other way, and change any tabs to 4-spaces throughout the code samples in the ReadMe doc.

**Comment by epayet** [comment]
No specific reason, the goal here was more to use [syntax highlighting ](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code).

I can change the tabs to spaces.

**Comment by epayet** [comment]
I just opened a cleaner PR with usage of syntax highlighting and 4 spaces, I am closing this in favour of [PR13](https://github.com/Microsoft/Kafkanet/pull/13)

**Comment by jthelin** [comment]
Hi @johnstark -- just FYI, you can just push additional commits to an existing PR branch on GitHub and it will be included in the eventual change set that would get merged into master. No need to create a new pull request.

**Comment by epayet** [comment]
Thanks for your tip, I just thought my commits messages were misleading, one says: 'Changed spaces to tabs' and another says 'Changed tabs to spaces'. I didn't like the commit history that it will show and preferred my other commit message on the other PR / branch.

Anyway, that wouldn't matter too much at the end, I guess ^^
Thanks for your time.

**Comment by jthelin** [comment]
You can also rewrite a PR branch with interactive rebase locally and then do a forced-push to clean up those kinds of things too!

Use sparingly [and never on `master` branch!], but rebase/forced push is completely appropriate for pull request branches for these edit scenarios.

GitHub is now pretty good at doing the right thing with incremental pull requests branches :)

**Comment by epayet** [comment]
Ok I get it! I didn't think of `rebase`. 
Thanks for the tip!

**Pull request closed without merging**
